version: '2.3'

services:
  caddy:
    image: caddy
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - ./.caddy/:/data
    ports:
      - 80:80
      - 443:443
      - 9001:9001
    restart: always

  minio: 
    image: minio/minio
    command: server /data  --console-address ":9001"
    restart: always
    volumes:
      - /home/exouser/data:/data
    env_file: ./config/minio_env.sh

  rstudio:
    image: rocker/rstudio:latest
    restart: always
    volumes:
      - /home/exouser:/home/rstudio
    env_file: ./config/rstudio_env.sh
    #command: /bin/bash -c "chown -R rstudio.rstudio /home/rstudio/; /init"
